/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package project

class App {
    val greeting: String
        get() {
            return "Hello World!ssssssssss"
        }
}

fun main() {
    println(App().greeting)

}
