/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package project

import kotlin.test.Test
import kotlin.test.assertEquals

class CompilerTest {
    @Test
    fun testTokenizerCanAnalyzeInput() {
        val result = tokenizer("(add 2 (subtract 4 2))")
        assertEquals(
            result, arrayListOf(
                Token("paren", "("),
                Token("name", "add"),
                Token("number", "2"),
                Token("paren", "("),
                Token("name", "subtract"),
                Token("number", "4"),
                Token("number", "2"),
                Token("paren", ")"),
                Token("paren", ")")
            )
        )
    }
}
